//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace CTe.v300 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/cte")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.portalfiscal.inf.br/cte", IsNullable=false)]
    public partial class duto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vTarField;
        
        private string dIniField;
        
        private string dFimField;
        
        /// <remarks/>
        public string vTar {
            get {
                return this.vTarField;
            }
            set {
                this.vTarField = value;
                this.RaisePropertyChanged("vTar");
            }
        }
        
        /// <remarks/>
        public string dIni {
            get {
                return this.dIniField;
            }
            set {
                this.dIniField = value;
                this.RaisePropertyChanged("dIni");
            }
        }
        
        /// <remarks/>
        public string dFim {
            get {
                return this.dFimField;
            }
            set {
                this.dFimField = value;
                this.RaisePropertyChanged("dFim");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
