//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace CTe.v300 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/cte")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.portalfiscal.inf.br/cte", IsNullable=false)]
    public partial class aquav : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vPrestField;
        
        private string vAFRMMField;
        
        private string xNavioField;
        
        private aquavBalsa[] balsaField;
        
        private string nViagField;
        
        private aquavDirec direcField;
        
        private string irinField;
        
        private aquavDetCont[] detContField;
        
        private aquavTpNav tpNavField;
        
        private bool tpNavFieldSpecified;
        
        /// <remarks/>
        public string vPrest {
            get {
                return this.vPrestField;
            }
            set {
                this.vPrestField = value;
                this.RaisePropertyChanged("vPrest");
            }
        }
        
        /// <remarks/>
        public string vAFRMM {
            get {
                return this.vAFRMMField;
            }
            set {
                this.vAFRMMField = value;
                this.RaisePropertyChanged("vAFRMM");
            }
        }
        
        /// <remarks/>
        public string xNavio {
            get {
                return this.xNavioField;
            }
            set {
                this.xNavioField = value;
                this.RaisePropertyChanged("xNavio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("balsa")]
        public aquavBalsa[] balsa {
            get {
                return this.balsaField;
            }
            set {
                this.balsaField = value;
                this.RaisePropertyChanged("balsa");
            }
        }
        
        /// <remarks/>
        public string nViag {
            get {
                return this.nViagField;
            }
            set {
                this.nViagField = value;
                this.RaisePropertyChanged("nViag");
            }
        }
        
        /// <remarks/>
        public aquavDirec direc {
            get {
                return this.direcField;
            }
            set {
                this.direcField = value;
                this.RaisePropertyChanged("direc");
            }
        }
        
        /// <remarks/>
        public string irin {
            get {
                return this.irinField;
            }
            set {
                this.irinField = value;
                this.RaisePropertyChanged("irin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detCont")]
        public aquavDetCont[] detCont {
            get {
                return this.detContField;
            }
            set {
                this.detContField = value;
                this.RaisePropertyChanged("detCont");
            }
        }
        
        /// <remarks/>
        public aquavTpNav tpNav {
            get {
                return this.tpNavField;
            }
            set {
                this.tpNavField = value;
                this.RaisePropertyChanged("tpNav");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tpNavSpecified {
            get {
                return this.tpNavFieldSpecified;
            }
            set {
                this.tpNavFieldSpecified = value;
                this.RaisePropertyChanged("tpNavSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/cte")]
    public partial class aquavBalsa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string xBalsaField;
        
        /// <remarks/>
        public string xBalsa {
            get {
                return this.xBalsaField;
            }
            set {
                this.xBalsaField = value;
                this.RaisePropertyChanged("xBalsa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/cte")]
    public enum aquavDirec {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        O,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/cte")]
    public partial class aquavDetCont : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nContField;
        
        private aquavDetContLacre[] lacreField;
        
        private aquavDetContInfDoc infDocField;
        
        /// <remarks/>
        public string nCont {
            get {
                return this.nContField;
            }
            set {
                this.nContField = value;
                this.RaisePropertyChanged("nCont");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lacre")]
        public aquavDetContLacre[] lacre {
            get {
                return this.lacreField;
            }
            set {
                this.lacreField = value;
                this.RaisePropertyChanged("lacre");
            }
        }
        
        /// <remarks/>
        public aquavDetContInfDoc infDoc {
            get {
                return this.infDocField;
            }
            set {
                this.infDocField = value;
                this.RaisePropertyChanged("infDoc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/cte")]
    public partial class aquavDetContLacre : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nLacreField;
        
        /// <remarks/>
        public string nLacre {
            get {
                return this.nLacreField;
            }
            set {
                this.nLacreField = value;
                this.RaisePropertyChanged("nLacre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/cte")]
    public partial class aquavDetContInfDoc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("infNF", typeof(aquavDetContInfDocInfNF))]
        [System.Xml.Serialization.XmlElementAttribute("infNFe", typeof(aquavDetContInfDocInfNFe))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/cte")]
    public partial class aquavDetContInfDocInfNF : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serieField;
        
        private string nDocField;
        
        private string unidRatField;
        
        /// <remarks/>
        public string serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
                this.RaisePropertyChanged("serie");
            }
        }
        
        /// <remarks/>
        public string nDoc {
            get {
                return this.nDocField;
            }
            set {
                this.nDocField = value;
                this.RaisePropertyChanged("nDoc");
            }
        }
        
        /// <remarks/>
        public string unidRat {
            get {
                return this.unidRatField;
            }
            set {
                this.unidRatField = value;
                this.RaisePropertyChanged("unidRat");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/cte")]
    public partial class aquavDetContInfDocInfNFe : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string chaveField;
        
        private string unidRatField;
        
        /// <remarks/>
        public string chave {
            get {
                return this.chaveField;
            }
            set {
                this.chaveField = value;
                this.RaisePropertyChanged("chave");
            }
        }
        
        /// <remarks/>
        public string unidRat {
            get {
                return this.unidRatField;
            }
            set {
                this.unidRatField = value;
                this.RaisePropertyChanged("unidRat");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/cte")]
    public enum aquavTpNav {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
}
