//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace CTe.v300 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/cte")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.portalfiscal.inf.br/cte", IsNullable=false)]
    public partial class rodoOS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private rodoOSVeic veicField;
        
        private rodoOSInfFretamento infFretamentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NroRegEstadual", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("TAF", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        /// <remarks/>
        public rodoOSVeic veic {
            get {
                return this.veicField;
            }
            set {
                this.veicField = value;
                this.RaisePropertyChanged("veic");
            }
        }
        
        /// <remarks/>
        public rodoOSInfFretamento infFretamento {
            get {
                return this.infFretamentoField;
            }
            set {
                this.infFretamentoField = value;
                this.RaisePropertyChanged("infFretamento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/cte", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        NroRegEstadual,
        
        /// <remarks/>
        TAF,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/cte")]
    public partial class rodoOSVeic : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string placaField;
        
        private string rENAVAMField;
        
        private rodoOSVeicProp propField;
        
        private TUf ufField;
        
        /// <remarks/>
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
                this.RaisePropertyChanged("placa");
            }
        }
        
        /// <remarks/>
        public string RENAVAM {
            get {
                return this.rENAVAMField;
            }
            set {
                this.rENAVAMField = value;
                this.RaisePropertyChanged("RENAVAM");
            }
        }
        
        /// <remarks/>
        public rodoOSVeicProp prop {
            get {
                return this.propField;
            }
            set {
                this.propField = value;
                this.RaisePropertyChanged("prop");
            }
        }
        
        /// <remarks/>
        public TUf UF {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
                this.RaisePropertyChanged("UF");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/cte")]
    public partial class rodoOSVeicProp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        private string item1Field;
        
        private Item1ChoiceType item1ElementNameField;
        
        private string xNomeField;
        
        private string ieField;
        
        private TUf ufField;
        
        private rodoOSVeicPropTpProp tpPropField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CNPJ", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("CPF", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NroRegEstadual", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("TAF", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Item1ElementName")]
        public string Item1 {
            get {
                return this.item1Field;
            }
            set {
                this.item1Field = value;
                this.RaisePropertyChanged("Item1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Item1ChoiceType Item1ElementName {
            get {
                return this.item1ElementNameField;
            }
            set {
                this.item1ElementNameField = value;
                this.RaisePropertyChanged("Item1ElementName");
            }
        }
        
        /// <remarks/>
        public string xNome {
            get {
                return this.xNomeField;
            }
            set {
                this.xNomeField = value;
                this.RaisePropertyChanged("xNome");
            }
        }
        
        /// <remarks/>
        public string IE {
            get {
                return this.ieField;
            }
            set {
                this.ieField = value;
                this.RaisePropertyChanged("IE");
            }
        }
        
        /// <remarks/>
        public TUf UF {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
                this.RaisePropertyChanged("UF");
            }
        }
        
        /// <remarks/>
        public rodoOSVeicPropTpProp tpProp {
            get {
                return this.tpPropField;
            }
            set {
                this.tpPropField = value;
                this.RaisePropertyChanged("tpProp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/cte", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        CNPJ,
        
        /// <remarks/>
        CPF,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/cte", IncludeInSchema=false)]
    public enum Item1ChoiceType {
        
        /// <remarks/>
        NroRegEstadual,
        
        /// <remarks/>
        TAF,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/cte")]
    public enum TUf {
        
        /// <remarks/>
        AC,
        
        /// <remarks/>
        AL,
        
        /// <remarks/>
        AM,
        
        /// <remarks/>
        AP,
        
        /// <remarks/>
        BA,
        
        /// <remarks/>
        CE,
        
        /// <remarks/>
        DF,
        
        /// <remarks/>
        ES,
        
        /// <remarks/>
        GO,
        
        /// <remarks/>
        MA,
        
        /// <remarks/>
        MG,
        
        /// <remarks/>
        MS,
        
        /// <remarks/>
        MT,
        
        /// <remarks/>
        PA,
        
        /// <remarks/>
        PB,
        
        /// <remarks/>
        PE,
        
        /// <remarks/>
        PI,
        
        /// <remarks/>
        PR,
        
        /// <remarks/>
        RJ,
        
        /// <remarks/>
        RN,
        
        /// <remarks/>
        RO,
        
        /// <remarks/>
        RR,
        
        /// <remarks/>
        RS,
        
        /// <remarks/>
        SC,
        
        /// <remarks/>
        SE,
        
        /// <remarks/>
        SP,
        
        /// <remarks/>
        TO,
        
        /// <remarks/>
        EX,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/cte")]
    public enum rodoOSVeicPropTpProp {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/cte")]
    public partial class rodoOSInfFretamento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private rodoOSInfFretamentoTpFretamento tpFretamentoField;
        
        private string dhViagemField;
        
        /// <remarks/>
        public rodoOSInfFretamentoTpFretamento tpFretamento {
            get {
                return this.tpFretamentoField;
            }
            set {
                this.tpFretamentoField = value;
                this.RaisePropertyChanged("tpFretamento");
            }
        }
        
        /// <remarks/>
        public string dhViagem {
            get {
                return this.dhViagemField;
            }
            set {
                this.dhViagemField = value;
                this.RaisePropertyChanged("dhViagem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/cte")]
    public enum rodoOSInfFretamentoTpFretamento {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
}
