//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace CTe.v300 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/cte")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.portalfiscal.inf.br/cte", IsNullable=false)]
    public partial class ferrov : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ferrovTpTraf tpTrafField;
        
        private ferrovTrafMut trafMutField;
        
        private string fluxoField;
        
        /// <remarks/>
        public ferrovTpTraf tpTraf {
            get {
                return this.tpTrafField;
            }
            set {
                this.tpTrafField = value;
                this.RaisePropertyChanged("tpTraf");
            }
        }
        
        /// <remarks/>
        public ferrovTrafMut trafMut {
            get {
                return this.trafMutField;
            }
            set {
                this.trafMutField = value;
                this.RaisePropertyChanged("trafMut");
            }
        }
        
        /// <remarks/>
        public string fluxo {
            get {
                return this.fluxoField;
            }
            set {
                this.fluxoField = value;
                this.RaisePropertyChanged("fluxo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/cte")]
    public enum ferrovTpTraf {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/cte")]
    public partial class ferrovTrafMut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ferrovTrafMutRespFat respFatField;
        
        private ferrovTrafMutFerrEmi ferrEmiField;
        
        private string vFreteField;
        
        private string chCTeFerroOrigemField;
        
        private ferrovTrafMutFerroEnv[] ferroEnvField;
        
        /// <remarks/>
        public ferrovTrafMutRespFat respFat {
            get {
                return this.respFatField;
            }
            set {
                this.respFatField = value;
                this.RaisePropertyChanged("respFat");
            }
        }
        
        /// <remarks/>
        public ferrovTrafMutFerrEmi ferrEmi {
            get {
                return this.ferrEmiField;
            }
            set {
                this.ferrEmiField = value;
                this.RaisePropertyChanged("ferrEmi");
            }
        }
        
        /// <remarks/>
        public string vFrete {
            get {
                return this.vFreteField;
            }
            set {
                this.vFreteField = value;
                this.RaisePropertyChanged("vFrete");
            }
        }
        
        /// <remarks/>
        public string chCTeFerroOrigem {
            get {
                return this.chCTeFerroOrigemField;
            }
            set {
                this.chCTeFerroOrigemField = value;
                this.RaisePropertyChanged("chCTeFerroOrigem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ferroEnv")]
        public ferrovTrafMutFerroEnv[] ferroEnv {
            get {
                return this.ferroEnvField;
            }
            set {
                this.ferroEnvField = value;
                this.RaisePropertyChanged("ferroEnv");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/cte")]
    public enum ferrovTrafMutRespFat {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/cte")]
    public enum ferrovTrafMutFerrEmi {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/cte")]
    public partial class ferrovTrafMutFerroEnv : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cNPJField;
        
        private string cIntField;
        
        private string ieField;
        
        private string xNomeField;
        
        private TEnderFer enderFerroField;
        
        /// <remarks/>
        public string CNPJ {
            get {
                return this.cNPJField;
            }
            set {
                this.cNPJField = value;
                this.RaisePropertyChanged("CNPJ");
            }
        }
        
        /// <remarks/>
        public string cInt {
            get {
                return this.cIntField;
            }
            set {
                this.cIntField = value;
                this.RaisePropertyChanged("cInt");
            }
        }
        
        /// <remarks/>
        public string IE {
            get {
                return this.ieField;
            }
            set {
                this.ieField = value;
                this.RaisePropertyChanged("IE");
            }
        }
        
        /// <remarks/>
        public string xNome {
            get {
                return this.xNomeField;
            }
            set {
                this.xNomeField = value;
                this.RaisePropertyChanged("xNome");
            }
        }
        
        /// <remarks/>
        public TEnderFer enderFerro {
            get {
                return this.enderFerroField;
            }
            set {
                this.enderFerroField = value;
                this.RaisePropertyChanged("enderFerro");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/cte")]
    public partial class TEnderFer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string xLgrField;
        
        private string nroField;
        
        private string xCplField;
        
        private string xBairroField;
        
        private string cMunField;
        
        private string xMunField;
        
        private string cEPField;
        
        private TUf ufField;
        
        /// <remarks/>
        public string xLgr {
            get {
                return this.xLgrField;
            }
            set {
                this.xLgrField = value;
                this.RaisePropertyChanged("xLgr");
            }
        }
        
        /// <remarks/>
        public string nro {
            get {
                return this.nroField;
            }
            set {
                this.nroField = value;
                this.RaisePropertyChanged("nro");
            }
        }
        
        /// <remarks/>
        public string xCpl {
            get {
                return this.xCplField;
            }
            set {
                this.xCplField = value;
                this.RaisePropertyChanged("xCpl");
            }
        }
        
        /// <remarks/>
        public string xBairro {
            get {
                return this.xBairroField;
            }
            set {
                this.xBairroField = value;
                this.RaisePropertyChanged("xBairro");
            }
        }
        
        /// <remarks/>
        public string cMun {
            get {
                return this.cMunField;
            }
            set {
                this.cMunField = value;
                this.RaisePropertyChanged("cMun");
            }
        }
        
        /// <remarks/>
        public string xMun {
            get {
                return this.xMunField;
            }
            set {
                this.xMunField = value;
                this.RaisePropertyChanged("xMun");
            }
        }
        
        /// <remarks/>
        public string CEP {
            get {
                return this.cEPField;
            }
            set {
                this.cEPField = value;
                this.RaisePropertyChanged("CEP");
            }
        }
        
        /// <remarks/>
        public TUf UF {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
                this.RaisePropertyChanged("UF");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/cte")]
    public enum TUf {
        
        /// <remarks/>
        AC,
        
        /// <remarks/>
        AL,
        
        /// <remarks/>
        AM,
        
        /// <remarks/>
        AP,
        
        /// <remarks/>
        BA,
        
        /// <remarks/>
        CE,
        
        /// <remarks/>
        DF,
        
        /// <remarks/>
        ES,
        
        /// <remarks/>
        GO,
        
        /// <remarks/>
        MA,
        
        /// <remarks/>
        MG,
        
        /// <remarks/>
        MS,
        
        /// <remarks/>
        MT,
        
        /// <remarks/>
        PA,
        
        /// <remarks/>
        PB,
        
        /// <remarks/>
        PE,
        
        /// <remarks/>
        PI,
        
        /// <remarks/>
        PR,
        
        /// <remarks/>
        RJ,
        
        /// <remarks/>
        RN,
        
        /// <remarks/>
        RO,
        
        /// <remarks/>
        RR,
        
        /// <remarks/>
        RS,
        
        /// <remarks/>
        SC,
        
        /// <remarks/>
        SE,
        
        /// <remarks/>
        SP,
        
        /// <remarks/>
        TO,
        
        /// <remarks/>
        EX,
    }
}
